# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define = "nginx" do |nginx| #nome da máquina
    nginx.vm.box = "ubuntu/focal64" #box linux centos/7
    nginx.vm.network "private_network", ip "10.0.0.10" #placa de rede
    # nginx.vm.network = "forwarded_port", guest: 80, host: 8080 #para direcionar portas
    nginx.vm.provider "virtualbox" do |vb| #provider
      vb.memory = "512"
      vb.cpus = 1
    end
    nginx.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
      sudo ufw allow "Nginx HTTP"
    SHELL
  end
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "ubuntu/focal64"
    frontend.vm.network "private_network", ip "10.0.0.21"
    frontend.vm.provider "virtualbox" do |vb|


end
